AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ApiName:
    Type: String
    Default: VtlAppSyncApi
  TableArn:
    Description: Arn della tabella "ProductsTable"
    Type: String
    Default: arn:aws:dynamodb:eu-west-1:923125397052:table/ProductsTable
  TableName:
    Type: String
    Default: ProductsTable

Resources:
  AppSyncDDBRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
      Policies:
        - PolicyName: DDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource: !Ref TableArn

  AppsyncCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com

  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Ref ApiName
      AuthenticationType: API_KEY
      LogConfig:
        CloudWatchLogsRoleArn: !GetAtt AppsyncCloudWatchRole.Arn
        FieldLogLevel: ALL

  GraphQLApiSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      DefinitionS3Location: ./graphQL/graphqlschema.vtl

  GraphQLDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Name: dynamoDB
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDDBRole.Arn
      DynamoDBConfig:
        AwsRegion: !Sub ${AWS::Region}
        TableName: !Ref TableName

  UpdateProductResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: GraphQLApiSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Mutation
      FieldName: updateProduct
      DataSourceName: !GetAtt GraphQLDataSource.Name
      RequestMappingTemplateS3Location: ./graphQL/resolvers/updateProduct/requestTemplate.vtl
      ResponseMappingTemplateS3Location: ./graphQL/resolvers/updateProduct/responseTemplate.vtl

  UpdateBrandResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: GraphQLApiSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Mutation
      FieldName: updateBrand
      DataSourceName: !GetAtt GraphQLDataSource.Name
      RequestMappingTemplateS3Location: ./graphQL/resolvers/updateBrand/requestTemplate.vtl
      ResponseMappingTemplateS3Location: ./graphQL/resolvers/updateBrand/responseTemplate.vtl

  ProductsListResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: GraphQLApiSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Query
      FieldName: productsList
      DataSourceName: !GetAtt GraphQLDataSource.Name
      RequestMappingTemplateS3Location: ./graphQL/resolvers/listProducts/requestTemplate.vtl
      ResponseMappingTemplateS3Location: ./graphQL/resolvers/listProducts/responseTemplate.vtl

  GetProductResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: GraphQLApiSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Query
      FieldName: getProduct
      DataSourceName: !GetAtt GraphQLDataSource.Name
      RequestMappingTemplateS3Location: ./graphQL/resolvers/getProduct/requestTemplate.vtl
      ResponseMappingTemplateS3Location: ./graphQL/resolvers/getProduct/responseTemplate.vtl

  ProductsByBrandResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: GraphQLApiSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Query
      FieldName: productsByBrand
      DataSourceName: !GetAtt GraphQLDataSource.Name
      RequestMappingTemplateS3Location: ./graphQL/resolvers/productsByBrand/requestTemplate.vtl
      ResponseMappingTemplateS3Location: ./graphQL/resolvers/productsByBrand/responseTemplate.vtl

  BrandsListResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: GraphQLApiSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Query
      FieldName: brandsList
      DataSourceName: !GetAtt GraphQLDataSource.Name
      RequestMappingTemplateS3Location: ./graphQL/resolvers/listBrands/requestTemplate.vtl
      ResponseMappingTemplateS3Location: ./graphQL/resolvers/listBrands/responseTemplate.vtl

  APIKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
